# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZwvM8VsEyrPUh3s8dNb2o4/6AiAimIeB7X40/7l/k8aJ+mIuMA+0eqpIgn+xOZa8JCSAjHUSmalEdvvCT2boJ9CbiME4juzBb1ljzHoogAKGCjrMQLc1zn+IaETXPAaXEGPYEBRWuhMe5Kff+X7he3/m6MLg0AUTdkdzIIDdZou/1O/A6ycphyVAqOur+xQh8yLYa+Mq+EO9ey6NpIh0e040PpKPXuKDs/NCzgxpZPkDqQl8kFsE5tdo5L3KyUs6c8x/pFuntr/optNRU7uzW1UV+X+jK2CAPbNt4sdATTQPZ+DVqaVRzv/TpdpyJqBnT0Q8jYXFNIG7ip8R6G+6o4/oYmbsVEIsahMoY3v4FQf7y/QBycNNV11fpTB7V2OidlOXyGQPugP8cizGFC+E57xmgWUI5d1MrQPd00qSgKEopIvhGLXQsr/Gyd+U+E2yjn6xhQQmpTWpZmpp4Mn13kKd1suFNSoTuFbR+n7VLEIZw6hbTzTDMlqg8p+qjsePZ+1k26iOTTqILL3U+dRURJgI3rGtOyVXXdb7raCRdCVVILkFta1yJTgUyJVsTE9W7HgWrsh+WX9NeaFytfbEp9BXH6qIj5aqVoLPrr4O+DVKYGIox1EzWuuSecbzjW7fNvphwAO0Kic1DTLxUDNNmL5YLWHxfF8MnGY+zapTaOo="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
