travis:
  secure:
    BINSTAR_TOKEN: ZwvM8VsEyrPUh3s8dNb2o4/6AiAimIeB7X40/7l/k8aJ+mIuMA+0eqpIgn+xOZa8JCSAjHUSmalEdvvCT2boJ9CbiME4juzBb1ljzHoogAKGCjrMQLc1zn+IaETXPAaXEGPYEBRWuhMe5Kff+X7he3/m6MLg0AUTdkdzIIDdZou/1O/A6ycphyVAqOur+xQh8yLYa+Mq+EO9ey6NpIh0e040PpKPXuKDs/NCzgxpZPkDqQl8kFsE5tdo5L3KyUs6c8x/pFuntr/optNRU7uzW1UV+X+jK2CAPbNt4sdATTQPZ+DVqaVRzv/TpdpyJqBnT0Q8jYXFNIG7ip8R6G+6o4/oYmbsVEIsahMoY3v4FQf7y/QBycNNV11fpTB7V2OidlOXyGQPugP8cizGFC+E57xmgWUI5d1MrQPd00qSgKEopIvhGLXQsr/Gyd+U+E2yjn6xhQQmpTWpZmpp4Mn13kKd1suFNSoTuFbR+n7VLEIZw6hbTzTDMlqg8p+qjsePZ+1k26iOTTqILL3U+dRURJgI3rGtOyVXXdb7raCRdCVVILkFta1yJTgUyJVsTE9W7HgWrsh+WX9NeaFytfbEp9BXH6qIj5aqVoLPrr4O+DVKYGIox1EzWuuSecbzjW7fNvphwAO0Kic1DTLxUDNNmL5YLWHxfF8MnGY+zapTaOo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
